services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:    # NOT NEEDED WHEN ALL THE SERVUCES ARE RUNNING IN THE DOCKER COMPOSE NETWORK
      - "3306:3306"  # NOT NEEDED WHEN ALL THE SERVUCES ARE RUNNING IN THE DOCKER COMPOSE NETWORK
    command: --lower_case_table_names=1  
    volumes:
      - mysql-data2:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s
      
      
  be:
    build: be/
    container_name: be
    restart: always
    env_file:
      - .env
    depends_on:
        mysql-db:
          condition: service_healthy
    
  nginx:
    build: fe/
    container_name: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./keystore/localhost.crt:/etc/nginx/localhost.crt
        - ./keystore/localhost.key:/etc/nginx/localhost.key  
    ports:
        - "443:443"
    restart: always

volumes:
  mysql-data2:
